### ISSUE TITLE
kann man dich per Mail erreichen?

### ISSUE THREAD

**Issue by zbiki** [odan/psr7-skeleton#2]
Moin Odan,
kann ich dich per Mail erreichen oder darf ich einfach hier fragen? Geht um dieses repos und dein slim4 skeleton.
mfg
christian

**Comment by odan** [comment]
Hallo Christian

Du kannst mich hier fragen oder per email: d.opitz (at) outlook (dot) com

**Comment by zbiki** [comment]
Moin odan,
danke! evtl. ist das ja noch für andere interessant. Ich nutze momentan slim3 für die Firma, habe irgendwie übersehen das es die Version 4 schon gab.
Da ich slim auch für private Projekte nutzen möchte bin ich mit Begeisterung auf dein slim4 skeleton gestoßen, wollte das auch direkt benutzen, bin nun aber auf dieses Projekt gestoßen und bin mir nicht mehr sicher ob ich den slim4 skeleton verwenden will oder diese Projekt als Basis für zukünftige private Projekte hernehmen soll. Meine Ideen kann ich mit beiden Projekten umsetzen, was würdest Du als Basis empfehlen? Was wäre sinnvoller um sich in aktuelles PHP einzuarbeiten? Ich tendiere zu psr7-skeleton, alles was ich mir angeschaut habe, schaut extrem gut aus und macht Lust es auszuprobieren. Ich hoffe du hast einen Tipp für mich, vielen Dank fürs Lesen.
mfg
Christian
-----
thank you! it might be interesting for others. I'm currently using slim3 for the company, I somehow overlooked that version 4 already existed.
Since I also want to use slim for private projects, I was enthusiastic about your slim4 skeleton and wanted to use it directly, but now I came across this project and am not sure anymore if I want to use the slim4 skeleton or use this project as a basis for future private projects. I can implement my ideas with both projects, what would you recommend as a basis? What would make more sense to get used to current PHP? I tend towards psr7-skeleton, everything I've looked at looks extremely good and makes me want to try it out. I hope you have a tip for me, thanks for reading.

Translated with www.DeepL.com/Translator

**Comment by odan** [comment]
Das psr7-skeleton basiert auf `league/container` und `league/route` . Das Slim-4 Skeleton basiert hauptsächlich auf Slim 4 und weiteren packages.

Ich persönlich würde ehr dazu raten Slim 4 bzw. das Slim-4 Skeleton zu verwenden wenn du schon gute Erfahrung mit Slim 3 gemacht hast. Meiner Erfahrung nach ist die Slim-Community auch viel grösser und aktiver als die von phpleage. Bei dem Container und Router package von thephpleage dauert es teils ewig bis man eine Antwort erhält (wenn überhaupt). Der allgemeine Support ist (meiner Meinung nach) bei Slim viel besser. Im Slim Forum und im Slack Channel gibt es fast immer eine Person die helfen kann. Aus diesen (und einigen anderen) Gründen kümmere ich mich in letzter Zeit wieder mehr um das Slim-4 Skeleton Projekt. 

**Fazit**: Als Basis für neue Projekte würde ich das Slim-4 skeleton empfehlen.

**Comment by zbiki** [comment]
Moin Odan,
vielen Dank! dann werde ich das hernehmen. Könnte sein das ich dich zum Thema Module noch mal was frage, falls ich mich traue und das Thema im Slim Forum für mich nicht aufschlussreich ist.
Dir ein angenehmes Wochenende
mfg
Christian

--

Thank you so much! Then I'll take that from you. Could be that I ask you something about modules again, if I dare and the topic in the Slim Forum is not informative for me.
You a pleasant weekend
mfg
Christian

Translated with www.DeepL.com/Translator

**Comment by odan** [comment]
Danke, ich wünsche dir ebenfalls ein schönes Wochenende.

--
Thank you, have a nice weekend.
